const CHANGE_IS_MOBILE = 'CHANGE_IS_MOBILE';
const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED';
const ADD_TAG_LIST = 'ADD_TAG_LIST';
const CUT_TAG_LIST = 'CUT_TAG_LIST';
const EMPTY_TAG_LIST = 'EMPTY_TAG_LIST';
const CUT_OTHER_TAG_LIST = 'CUT_OTHER_TAG_LIST';
const SET_TOKEN = 'SET_TOKEN';
const REMOVE_TOKEN = 'REMOVE_TOKEN';
const SET_USER_INFO = 'SET_USER_INFO';
const SHOW_LOADING = 'SHOW_LOADING';
const HIDE_LOADING = 'HIDE_LOADING';


export {
    CHANGE_IS_MOBILE,
    CHANGE_COLLAPSED,
    ADD_TAG_LIST,
    CUT_TAG_LIST,
    EMPTY_TAG_LIST,
    CUT_OTHER_TAG_LIST,
    SET_TOKEN,
    REMOVE_TOKEN,
    SET_USER_INFO,
    SHOW_LOADING,
    HIDE_LOADING
}
